name: Feature request
description: Suggest an enhancement (new prop, new plugin, behavior change)
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Your proposed change
      description: API sketch / code snippet
